### PR TITLE
Fix inline math

### PR DESCRIPTION
**Pull request by nsoranzo**
with code from:

readthedocs/recommonmark#124
readthedocs/recommonmark#178
readthedocs/recommonmark#194

Fix the following traceback:

```
.venv/lib/python3.6/site-packages/sphinx/application.py:342: in build
    self.builder.build_all()
.venv/lib/python3.6/site-packages/sphinx/builders/__init__.py:260: in build_all
    self.build(None, summary=__('all source files'), method='all')
.venv/lib/python3.6/site-packages/sphinx/builders/__init__.py:311: in build
    updated_docnames = set(self.read())
.venv/lib/python3.6/site-packages/sphinx/builders/__init__.py:418: in read
    self._read_serial(docnames)
.venv/lib/python3.6/site-packages/sphinx/builders/__init__.py:439: in _read_serial
    self.read_doc(docname)
.venv/lib/python3.6/site-packages/sphinx/builders/__init__.py:479: in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
.venv/lib/python3.6/site-packages/sphinx/io.py:221: in read_doc
    pub.publish()
.venv/lib/python3.6/site-packages/docutils/core.py:219: in publish
    self.apply_transforms()
.venv/lib/python3.6/site-packages/docutils/core.py:200: in apply_transforms
    self.document.transformer.apply_transforms()
.venv/lib/python3.6/site-packages/sphinx/transforms/__init__.py:86: in apply_transforms
    super().apply_transforms()
.venv/lib/python3.6/site-packages/docutils/transforms/__init__.py:171: in apply_transforms
    transform.apply(**kwargs)
sphinx_markdown_parser/transform.py:345: in apply
    self.traverse(self.document)
sphinx_markdown_parser/transform.py:323: in traverse
    self.traverse(child)
sphinx_markdown_parser/transform.py:323: in traverse
    self.traverse(child)
sphinx_markdown_parser/transform.py:313: in traverse
    newnode = self.find_replace(c)
sphinx_markdown_parser/transform.py:297: in find_replace
    newnode = self.auto_inline_code(node)
sphinx_markdown_parser/transform.py:220: in auto_inline_code
    return self.state_machine.run_role('math', content=content)
sphinx_markdown_parser/states.py:123: in run_role
    content=content

role = 'math', rawtext = ' E = mc^2 ', text = ' E = mc^2 ', lineno = 4, inliner = <docutils.parsers.rst.states.Inliner object at 0x7fe9758a2518>, options = {}, content = ' E = mc^2 '

    def math_role(role, rawtext, text, lineno, inliner, options={}, content=[]):
        set_classes(options)
        i = rawtext.find('`')
>       text = rawtext.split('`')[1]
E       IndexError: list index out of range

.venv/lib/python3.6/site-packages/docutils/parsers/rst/roles.py:361: IndexError
```

### CODE REVIEW

**Comment by clayrisser** [comment]
Thanks for filing this issue

**Comment by nsoranzo** [comment]
> Thanks for filing this issue

@codejamninja Actually it's a PR ;) (not to nitpick, just to be sure you haven't missed that).

**Comment by clayrisser** [comment]
Cool I just merged it. I’ll publish it soon.

**Comment by nsoranzo** [comment]
Thanks a lot!

**Pull request merged**
