### PR TITLE
Rewrite markdown_parser so it actually works

### PR DESCRIPTION
**Pull request by infinity0**
Hi, I couldn't get your parser to work so I rewrote it, my version supports more stuff (raw html and tables) as well as the latest version of docutils / sphinx, and IMO is easier to understand - no repetitive traversal boilerplate.

Please let me know if it looks good and you're happy to upload to PyPI under the current package name `sphinx_markdown_parser`, otherwise I'll fork it as I really need this functionality pretty urgently.

### CODE REVIEW

**Comment by infinity0** [comment]
(The tests are failing, but they were also failing before my PR.)

**Comment by clayrisser** [comment]
I'm really happy. Thanks for this work. I might reach out to you if there are bugs. Since this is such a large commit, would you mind if I give you access to the repo to prevent me from blocking potential bug fixes?

**Comment by clayrisser** [comment]
I just published a new release with these changes. `v0.2.0`

**Comment by infinity0** [comment]
That's awesome, thanks! I just noticed a few minor bugs so will send another PR today. If you want, you can also give the "infinity0" account on PyPI upload access to the package.

**Comment by clayrisser** [comment]
Sure, I really appreciate this. I build this for myself, but a lot of people started using it. I've been doing my best to keep it up to date, but am a bit too busy to manage it all myself in a timely fashion. I really appreciate the help.

**Comment by clayrisser** [comment]
@infinity0  I added you to pypi and github

**Comment by infinity0** [comment]
Great, thanks!

**Pull request merged**
